name: Swift Builds
on: [push]

jobs:
  build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: swift-actions/setup-swift@v1
      - uses: actions/checkout@v4
      - name: Get Swift version
        run: swift --version
      - name: Run Swift build
        run: swift build
